### ISSUE TITLE
No rule to make target '_build/system_nrf51.o', needed by 'all'

### ISSUE THREAD

**Issue by liubenyuan** [hlnd/nrf51-pure-gcc-setup#10]
Hi,

I followed the steps in
http://qiita.com/mkftr/items/6144fbb3f20e124731bf

However, in the blinky example, when I type make, it yield

```
make: *** No rule to make target '_build/system_nrf51.o', needed by 'all'.  Stop.
```

all the cross toolchains are installed, any hint ?

**Comment by liubenyuan** [comment]
Opps, it was my mistake, I set up the wrong SDK folder, the correct one should be
$(HOME)/nordic/nrf51_sdk_v5_2_0_39364/Nordic/nrf51822

One more problem, when I type
make
it generated:

```
[postgres@by pure-gcc]$ make
mkdir -p _build/
arm-none-eabi-gcc -mthumb -mcpu=cortex-m0 -march=armv6-m -L /home/postgres/sketchbook/nrf51822/nrf51-pure-gcc-setup/template/ -T gcc_nrf51_blank.ld -Wl,-Map=_build/blinky_example_blank.Map -Os -std=gnu99 -c -mthumb -mcpu=cortex-m0 -march=armv6-m -Wall -DNRF51 -DBOARD_PCA10001 -I/home/postgres/sketchbook/nrf51822/nrf51_sdk_v5_2_0_39364/Nordic/nrf51822/Include/gcc -I../ -I/home/postgres/sketchbook/nrf51822/nrf51_sdk_v5_2_0_39364/Nordic/nrf51822/Include/ -MD /home/postgres/sketchbook/nrf51822/nrf51_sdk_v5_2_0_39364/Nordic/nrf51822/Source/templates/system_nrf51.c -o _build/system_nrf51.o
mkdir -p _build/
arm-none-eabi-gcc -mthumb -mcpu=cortex-m0 -march=armv6-m -L /home/postgres/sketchbook/nrf51822/nrf51-pure-gcc-setup/template/ -T gcc_nrf51_blank.ld -Wl,-Map=_build/blinky_example_blank.Map -Os -std=gnu99 -c -mthumb -mcpu=cortex-m0 -march=armv6-m -Wall -DNRF51 -DBOARD_PCA10001 -I/home/postgres/sketchbook/nrf51822/nrf51_sdk_v5_2_0_39364/Nordic/nrf51822/Include/gcc -I../ -I/home/postgres/sketchbook/nrf51822/nrf51_sdk_v5_2_0_39364/Nordic/nrf51822/Include/ -MD /home/postgres/sketchbook/nrf51822/nrf51_sdk_v5_2_0_39364/Nordic/nrf51822/Source/nrf_delay/nrf_delay.c -o _build/nrf_delay.o
mkdir -p _build/
arm-none-eabi-as /home/postgres/sketchbook/nrf51822/nrf51-pure-gcc-setup/template/startup_nrf51.s -o _build/startup_nrf51.os
arm-none-eabi-gcc -mthumb -mcpu=cortex-m0 -march=armv6-m -L /home/postgres/sketchbook/nrf51822/nrf51-pure-gcc-setup/template/ -T gcc_nrf51_blank.ld -Wl,-Map=_build/blinky_example_blank.Map _build/startup_nrf51.os _build/system_nrf51.o _build/nrf_delay.o  -o _build/blinky_example_blank.elf
/usr/lib/gcc/arm-none-eabi/4.9.0/../../../../arm-none-eabi/lib/thumb/cortex-m0/crt0.o: In function `_start':
/build/arm-none-eabi-gcc/src/gcc-4.9.0/build/arm-none-eabi/thumb/cortex-m0/libgloss/arm/../../../../../../libgloss/arm/crt0.S:420: undefined reference to `main'
collect2: error: ld returned 1 exit status
/home/postgres/sketchbook/nrf51822/nrf51-pure-gcc-setup/template/Makefile:99: recipe for target '_build/blinky_example_blank.hex' failed
make: *** [_build/blinky_example_blank.hex] Error 1
```

**Comment by JoeMerten** [comment]
What cross toolchain are you using?
As far as I know, you need the gnu arm toolchain from https://launchpad.net/gcc-arm-embedded, e.g. like:

```
wget https://launchpadlibrarian.net/170926605/gcc-arm-none-eabi-4_8-2014q1-20140314-linux.tar.bz2
sudo mkdir -p /opt
sudo tar -xjf gcc-arm-none-eabi-4_8-2014q1-20140314-linux.tar.bz2 -C/opt
```

It seems that CodeSourcery is not supported.

**Comment by liubenyuan** [comment]
I am using arch linux `arm-none-eabi-gcc` package, 

```
Using built-in specs.
COLLECT_GCC=arm-none-eabi-gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-none-eabi/4.9.0/lto-wrapper
Target: arm-none-eabi
Configured with: ../configure --target=arm-none-eabi --prefix=/usr --libexecdir=/usr/lib --with-pkgversion='Arch Repository' --with-bugurl=https://bugs.archlinux.org/ --enable-multilib --enable-interwork --enable-languages=c,c++ --with-newlib --with-gnu-as --with-gnu-ld --disable-nls --disable-shared --disable-threads --with-headers=newlib/libc/include --disable-libssp --disable-libstdcxx-pch --disable-libmudflap --disable-libgomp --with-system-zlib --disable-newlib-supplied-syscalls
Thread model: single
gcc version 4.9.0 (Arch Repository) 
```

I think that might be the problem...

**Comment by JoeMerten** [comment]
Well, nice to see your tryout with gcc 4.9 - I havn't tried that until now.
Yes, it looks a bit close to bleeding edge and may cause this problems.

I'd tried CodeSourcery (4.8) some weeks ago and got similar error messages (undefined reference).
But with gnu-arm (binaries from the links above), these messages are gone (tried with different versions of gcc 4.7 and 4.8 series).

I also use -flto to reduce code size and it works well (no longer need for -ffunction-sections -fdata-sections -Wl,--gc-sections).

**Comment by liubenyuan** [comment]
Hi, 

I had success with gcc-4.9.0 using the Makefiles provided by nordic. I post them here
`https://github.com/liubenyuan/nrf51822-makefile` . However, I like the structure of your `Makefile` and think the variables in the `Makefile` + `Makefile.config` is a little bit mess.

BTW, compared with the makefile provided by nordic, can you figure out how to make your makefile work ? I am glad to test your new script.

Liu

**Comment by JoeMerten** [comment]
This setup here is made by Ole Morten, not by me. I'm just a user of its work.
Maybe Ole could help further?

**Comment by hlnd** [comment]
Sorry for the delay here, but I'm having some trouble replicating this. I'm on Ubuntu/Debian, so I don't have easy access to 4.9.0 (There are no builds on launchpad, and the Arch package, when manually unpacked, seems to behave oddly, not accepting neither -mcpu nor -march). 

I'd therefore primarily recommend you to check behavior with one of the zipped toolchains from [lauchpad](https://launchpad.net/gcc-arm-embedded), for instance one of the 4.8. 

However, for completeness: If you just symlink the pure-gcc folder into your project, you may see weird errors. At least for testing, I suggest you try copying the entire pure-gcc folder from examples/pca10001/blinky_project/ to $(SDK_PATH)/Board/pca10001/blinky_example/ and then try to run make from the pure-gcc subfolder. Make sure to remove all _build folders first.

**Comment by hlnd** [comment]
I hope that no further comments means that you got things working, so I'm closing this. Feel free to reopen and add further explanation should you still have problems!

**Comment by nocko** [comment]
Also using 4.9 from arch repos. Error still present. I did as you suggested: ' copying the entire pure-gcc folder from examples/pca10001/blinky_project/ to $(SDK_PATH)/Board/pca10001/blinky_example/ and then try to run make from the pure-gcc subfolder'. Still, the error remains make: **\* No rule to make target '_build/system_nrf51.o', needed by 'all'.  Stop.

It doesn't seem to have anything to do with the toolchain; the compiler, assembler nor linker is invoked before this error is returned.

**Comment by nocko** [comment]
Update, Makefile is not tolerant of spaces in the SDK_PATH. Changing this path to one without spaces seems to resolve this issue for me.

**Comment by liubenyuan** [comment]
@nocko 

Hi, as long as gcc-4.9 is concerned, you might want to try `https://github.com/liubenyuan/nrf51822-makefile` temporary and it works for me.

**Comment by hlnd** [comment]
I'm sorry, I actually managed to overlook the new comments here. However, do I understand it right that you got things working with 4.9 when having SDK_PATH without spaces? Unfortunately, I can very well imagine such spaces being problematic as I haven't quite found a good way of dealing with spaces from Makefiles... :-/ Pull requests or suggestion would be very welcome if there are any good tricks that I'm missing!

**Comment by nocko** [comment]
Yes. As long as SDK_PATH has no spaces, things work as expected.
