### ISSUE TITLE
build a BLE app using these templates

### ISSUE THREAD

**Issue by akohlsmith** [hlnd/nrf51-pure-gcc-setup#12]
Have you been able to compile any of the example BLE applications with this template? I found I had to add additional SOURCE_PATHS and INCLUDE_PATHS defines if USE_BLE was used (app_common, sd_common, ble, ble/ble_services, etc.) and even then once I finally got far enough along that it looked like it was going to work, the BLE source files would fail from what looks like missing/incorrect includes...

e.g. device_manager.c won't build because it has no idea what ble_gap_sec_keyset_t is since it the s110 softdevice header doesn't have it, but the s120 includes do.

**Comment by eliotstock** [comment]
I haven't updated since before the last few commits, so I'm a bit out of
date but yes, I was able to build the BLE proximity example code I think.

I had to add a bunch of SDK sources to APPLICATION_SRCS. I also added
-DBLE_STACK_SUPPORT_REQD to CFLAGS. Don't think I touched SOURCE_PATHS and
I don't seem to have an INCLUDE_PATHS defined.

Haven't used device_manager.c so not sure what's going on there sorry.

Eliot

**Comment by akohlsmith** [comment]
I've got everything building now, but I have not yet been successful in getting any of the BLE apps to show up in a BLE scan from my iPhone. my Fitbit Flex and a Quintic module show up so I know the phone is working correctly.

I'm using the s110_nrf51822_5.2.1_softdevice.hex which is what I built for (USE_SOFTDEVICE=s110). The blinky demo alternately blinks the LEDs on the PCA10001 I have, and I've tried make erase-all ; make flash-softdevice ; make flash as well as a make recover to see if I was stuck in some odd hardware mode... nothing seems to get this thing out on the air.

Have you seen this before?

**Comment by hlnd** [comment]
Sorry for the delay in responding to this issue, but it seems there is some misunderstanding here. 

First, there are example Makefiles in the repository for both [ble_app_proximity](https://github.com/hlnd/nrf51-pure-gcc-setup/blob/master/examples/pca10001/s110/ble_app_proximity/pure-gcc/Makefile) and [ble_app_hrs](https://github.com/hlnd/nrf51-pure-gcc-setup/blob/master/examples/pca10001/s110/ble_app_hrs/pure-gcc/Makefile) for PCA10001. There are no examples for nRF6310, but it should be pretty easy to adjust the files to make this work. 

Secondly, you must make sure to use the correct set of template files with the correct SDK with the correct softdevice. master of this repository works with SDK 5.2.0 and S110 version 6.0.0, but I've branched at all SDK releases lately, making it easy to go back to such version. However, there isn't really any reason to use anything earlier than SDK 5.2.0 and S110 version 6.0.0 as of today so I would strongly recommend you not to. 

You can look at the release notes of any given SDK to see which softdevice versions it works with. 

Thirdly, to get all include paths set up correctly for a softdevice, it is sufficient to set the USE_SOFTDEVICE in the project's makefile to the (lowercase!) name of the softdevice in question, typically "s110". 

Finally, if you can't get anything working, I'd recommend you to try running the project with a debugger. You should start with blinky, making sure to erase everything and then seeing that it runs. Having verified this, you should flash the correct softdevice version to the chip, and then the application you want to test.

**Comment by akohlsmith** [comment]
I have not mentioned anything about the nRF6310; all the things I'm doing are with the nRF51822.

I flashed the 6.0.0 softdevice and replaced the contents of the API's include/s110 directory with the contents of the 6.0.0 API's include directory and things are working much better.

The commit I had seems to be required to build even the two BLE examples you have with the 5.2.1 API as shipped by Nordic, but they are not required for the 6.0.0 API. I am not able to get the radio to function with the 5.2.1 softdevice but with the 6.0.0 softdevice it works immediately.

I did start with blinky, and it worked great. I have also now built the proximity test and now the nrf51-ble-app-temp app and they both work well. I think I'm over this hurdle and ready to run headlong into the next. :-)

Thank you for your assistance, I am now on my way with your templates!

**Comment by hlnd** [comment]
The nRF6310 is just another board (to use the Development Kit with, PCA10004/10005), and the projects there are also for the nRF51822.

As for 5.2.1, it is not compatible with the latest SDK, and as I said, you must make sure to use the correct template/SDK/softdevice combo. Hence, you have to checkout the 4.4.2 branch to get 5.2.1, as that SDK is compatible with S110 5.2.1. This branch uses a slightly different setup, but if you do things correctly (as indicated by the example makefiles), no changes to the template files should be needed. 

Anyway, I'm closing this for now, as it sounds as if you've gotten further! :-)

**Comment by akohlsmith** [comment]
Ahh, it was not clear to me that master was for s110 version 6.0.0 and branch 4.4.2 was for s110 version 5.2.0/1. Your s110/7.0.0alpha branch is however very clearly named! :-)

**Comment by hlnd** [comment]
As I said in my initial comment: "master of this repository works with SDK 5.2.0 and S110 version 6.0.0, but I've branched at all SDK releases lately, making it easy to go back to such version."

Also, as I said, the SDK version is tied to a softdevice version, as given in the SDK's release notes.

Anyway, let's leave this for now.
