### ISSUE TITLE
S110 v7.0.0 release needs new offset

### ISSUE THREAD

**Issue by janekm** [hlnd/nrf51-pure-gcc-setup#17]
-  FLASH (rx) : ORIGIN = 0x15000, LENGTH = 0x2B000 /\* 84 kB is taken by S110, 172 kB for app. */
-  FLASH (rx) : ORIGIN = 0x16000, LENGTH = 0x2A000 /\* S110 v7.0.0 release starts at 0x00016000 */

**Comment by liamstask** [comment]
Found I needed to adjust this as well.

For clarity, I also find it's nice to represent the offsets in terms of kB:

```
FLASH (rx) : ORIGIN = 0x00000000 + 88K, LENGTH = 256K - 88K /* 88 kB is taken by S110, 168 kB for app. */
RAM (rwx) :  ORIGIN = 0x20000000 + 8K,  LENGTH = 16K - 8K   /* 8 kB is taken by S110,8 kB for app. */
```

**Comment by hlnd** [comment]
Thanks for letting me know Janek, and also thanks for the nice syntax suggestion Liam! Both are now fixed in master.
